language: node_js
node_js:
 - 12
install:
 - npm i
script:
 - npm run test

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  github-token: abc35c63931c5f096596538ec34798eefe6130f7
  keep-history: true
  target_branch: master
  on:
    branch: master