language: node_js
node_js:
  - "stable"
before_install:
  - npm install -g npm@latest
  - npm run babel:compile
install:
  - npm i
script: 
  - npm run test:nocoverage
after_success: 
  - npm run test:coverage && npm run coverage